/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class my_snippets_jni_CalculadoraJNI */

#ifndef _Included_my_snippets_jni_CalculadoraJNI
#define _Included_my_snippets_jni_CalculadoraJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     my_snippets_jni_CalculadoraJNI
 * Method:    soma
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_my_snippets_jni_CalculadoraJNI_soma
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
