/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class my_snippets_jni_HelloWorld */

#ifndef _Included_my_snippets_jni_HelloWorld
#define _Included_my_snippets_jni_HelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     my_snippets_jni_HelloWorld
 * Method:    print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_my_snippets_jni_HelloWorld_print
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
